import favicon from '@/app/favicon.ico';
import styles from '@/app/styles/BackgroundTriangles.module.css';
import type { Metadata } from 'next';
import type { FunctionComponent, ReactNode } from 'react';
type LayoutProps = {
    children?: ReactNode;
};

export const metadata: Metadata = {
    title: 'Login',
    description: 'Generated by create next app',
    icons: {
        icon: favicon.src,
    },
};

const RootLayout: FunctionComponent<LayoutProps> = ({ children }) => {
    return (
        <html lang='es'>
            <body>
                <main className={styles.BackgroundTriangles}>{children}</main>
            </body>
        </html>
    );
};

export default RootLayout;
