import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import type { FunctionComponent, ReactNode } from 'react';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'ViMarket3d',
    description: 'Generated by create next app',
    icons: {
        icon: '/favicon.ico',
    },
    openGraph: {
        title: 'ViMarket3d',
        description: 'Generated by create next app',
        url: 'https://www.vimarket3d.com/',
        siteName: 'ViMarket3d',
        // images: ['/favicon.ico'],
        locale: 'es-ES',
        type: 'website',
    },
};

type RootLayoutProps = Readonly<{
    children: ReactNode;
    // metadata: Metadata;
}>;

const RootLayout: FunctionComponent<RootLayoutProps> = ({
    children,
    // metadata
}) => {
    return (
        <html lang='es'>
            <body className={inter.className}>{children}</body>
        </html>
    );
};

export default RootLayout;
